# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exam', '0002_auto_20200615_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u540d\u79f0')),
                ('begin_time', models.DateTimeField(db_index=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('minutes', models.PositiveSmallIntegerField(default=60, verbose_name='\u9650\u65f6(\u5206\u949f)')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6709\u6548')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7')),
                ('owner_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b')),
            ],
            options={
                'verbose_name': '\u8003\u8bd5',
                'verbose_name_plural': '\u8003\u8bd5',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-create_time',), 'verbose_name': '\u7528\u6237\u7b54\u5377', 'verbose_name_plural': '\u7528\u6237\u7b54\u5377'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ('-is_active', 'order_number', '-create_time'), 'verbose_name': '\u8bd5\u5377', 'verbose_name_plural': '\u8bd5\u5377'},
        ),
        migrations.AlterField(
            model_name='paper',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
    ]
