# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-02 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0003_auto_20200626_0511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-is_active', '-begin_time'), 'verbose_name': '\u8003\u8bd5', 'verbose_name_plural': '\u8003\u8bd5'},
        ),
        migrations.AddField(
            model_name='exam',
            name='actual_user_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='\u5b9e\u9645\u53c2\u4e0e\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_user_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u76ee\u6807\u53c2\u4e0e\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_user_tags',
            field=models.TextField(blank=True, help_text='\u7b26\u5408\u6807\u7b7e\u7684\u4eba\u624d\u80fd\u586b\u5199\u95ee\u5377,\u7559\u7a7a\u5219\u6240\u6709\u4eba\u5747\u53ef\u586b\u5199\u4f46\u4e0d\u4f1a\u53d1\u4e2a\u4eba\u901a\u77e5.<p>\u4f8b\u5b50:<p>\u8001\u5e08:\u5f20\u4e09,\u674e\u56db,\u8d75\u4e94<p>\u5b66\u751f:*<p>\u5b66\u751f.\u5e74\u7ea7:\u5927\u4e00,\u5927\u4e8c<p>\u5b66\u751f.\u5165\u5b66\u5c4a\u522b:2019\u5c4a<p>\u5b66\u751f.\u73ed\u7ea7:2018\u7ea7\u6570\u5b57\u5a92\u4f53201801\u73ed,2018\u7ea7\u6570\u5b57\u5a92\u4f53201804\u73ed', null=True, verbose_name='\u76ee\u6807\u4eba\u7fa4\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_users',
            field=models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='\u53c2\u4e0e\u4eba'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u5355\u9009'), (2, '\u591a\u9009'), (3, '\u586b\u7a7a'), (4, '\u4e3b\u89c2'), (5, '\u7b80\u7b54'), (6, '\u5224\u65ad\u6539\u9519')], db_index=True, default=4, verbose_name='\u7c7b\u522b'),
        ),
    ]
