# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-09-15 03:21
from __future__ import unicode_literals

from django.db import migrations
import xyz_util.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_answer_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade_detail',
            field=xyz_util.modelutils.JSONField(default={}, verbose_name='\u6279\u5377'),
            preserve_default=False,
        ),
    ]
