# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-09-17 02:32
from __future__ import unicode_literals

from django.db import migrations
import xyz_util.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_answer_grade_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade_detail',
            field=xyz_util.modelutils.JSONField(blank=True, verbose_name='\u6279\u5377'),
        ),
    ]
