# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-09-29 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200917_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='manual_grade',
            field=models.BooleanField(default=False, verbose_name='\u4eba\u5de5\u8bc4\u5206'),
        ),
    ]
