# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-07 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_exam_manual_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u6709\u6548'),
        ),
    ]
